apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
spec:
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: sumitkumar001/golang:1.17.0-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080